apiVersion: v1
kind: ConfigMap
metadata:
  name: cilium-values
  namespace: kube-system
data:
  values.yaml: |
    upgradeCompatibility: "1.8"
    k8sServiceHost: "localhost"
    k8sServicePort: "7445"
    securityContext:
      capabilities: 
        ciliumAgent:
          - CHOWN
          - KILL
          - NET_ADMIN
          - NET_RAW
          - IPC_LOCK
          - SYS_ADMIN
          - SYS_RESOURCE
          - DAC_OVERRIDE
          - FOWNER
          - SETGID
          - SETUID
        cleanCiliumState:
          - NET_ADMIN
          - SYS_ADMIN
          - SYS_RESOURCE
    l2podAnnouncements:
      enabled: true
    gatewayAPI:
      enabled: true
      enableAlpn: true
      enableAppProtocol: true
    hubble:
      metrics:
        enabled: 
          - dns
          - drop
          - tcp
          - flow
          - port-distribution
          - icmp
          - httpV2:exemplars=true;labelsContext=source_ip,source_namespace,source_workload,destination_ip,destination_namespace,destination_workload,traffic_direction
        enableOpenMetrics: true
        relay:
          enabled: true
          prometheus:
            enabled: true
        ui:
          enabled: true
    ipam:
      mode: "kubernetes"
    kubeProxyReplacement: "true"
    l2NeighDiscovery:
      enabled: true
    prometheus:
      enabled: true
    cgroup:
      autoMount:
        enabled: true
      hostRoot: /sys/fs/cgroup
